[package]
name = "lekhni-shell-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
lekhni-base = { path = "../lekhni-base" }
lekhni-text = { path = "../lekhni-text" }
lekhni-md = { path = "../lekhni-md" }
lekhni-raster = { path = "../lekhni-raster" }
lekhni-shell = { path = "../lekhni-shell" }
lekhni-ui = { path = "../lekhni-ui" }
lekhni-layout = { path = "../lekhni-layout" }
lekhni-store = { path = "../lekhni-store" }
