[package]
name = "lekhni-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["alloc"]
alloc = [
    "lekhni-base/alloc",
    "lekhni-text/alloc",
    "lekhni-shell/alloc",
]

[dependencies]
lekhni-base = { path = "../lekhni-base", default-features = false }
lekhni-text = { path = "../lekhni-text", default-features = false }
lekhni-shell = { path = "../lekhni-shell", default-features = false }
